apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-deployment
  labels:
    app: react-todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
      - name: react-todo-image
        image: niteshsngh/react-todo-app
        ports:
        - containerPort: 8001


apiVersion: v1
kind: Service
metadata:
  name: react-todo-service
spec:
  selector:
    app: react-todo
  ports:
    - port: 8001
      targetPort: 8090
  type: LoadBalancer
